### ISSUE TITLE
mailgun 处于试用期阶段，需要替代品

### ISSUE THREAD

**Issue by SignorMercurio** [ECNU-Forum/ECNU-Forum#1]

**Comment by jjaychen1e** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [mailgun 处于试用期阶段，需要替代品](https://trello.com/c/trqwT5Xe/7-mailgun-%E5%A4%84%E4%BA%8E%E8%AF%95%E7%94%A8%E6%9C%9F%E9%98%B6%E6%AE%B5%EF%BC%8C%E9%9C%80%E8%A6%81%E6%9B%BF%E4%BB%A3%E5%93%81)

**Comment by SignorMercurio** [comment]
新方案：Yandex.Mail
