### ISSUE TITLE
贴子的图片分辨率

### ISSUE THREAD

**Issue by chguw** [ECNU-Forum/ECNU-Forum#10]
现在论坛的贴子的图片是全分辨率展示的，建议改为先展示缩略图，点击之后才展开全分辨率

**Comment by SignorMercurio** [comment]
现在新上传的应该可以了

**Comment by jjaychen1e** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [贴子的图片分辨率](https://trello.com/c/3vStOrtD/22-%E8%B4%B4%E5%AD%90%E7%9A%84%E5%9B%BE%E7%89%87%E5%88%86%E8%BE%A8%E7%8E%87)
