### ISSUE TITLE
屏幕宽度不足时显示错位问题 & 分享功能

### ISSUE THREAD

**Issue by chguw** [ECNU-Forum/ECNU-Forum#15]
1 排版问题。这三张分别是 Windows 系统非最大化窗口、iPad 竖版和横版的单个主题页面。排版问题存在于顶部，从搜索框开始位置就错位了

<a href="https://imgtu.com/i/qiZ0e0"><img src="https://s1.ax1x.com/2022/03/18/qiZ0e0.png" alt="qiZ0e0.png" border="0"></a>
<a href="https://imgtu.com/i/qiZdLq"><img src="https://s1.ax1x.com/2022/03/18/qiZdLq.jpg" alt="qiZdLq.jpg" border="0"></a>
<a href="https://imgtu.com/i/qiZayn"><img src="https://s1.ax1x.com/2022/03/18/qiZayn.jpg" alt="qiZayn.jpg" border="0"></a>

2 通知中心的小铃铛不会自动清零，就算浏览了相应的主题也不会，必须点勾勾才行。电脑端影响还好，移动端因为底部 Tab 有“通知中心”，不停地提示着未读信息（实际上我已经都浏览了，只是没有点勾勾给它清掉而已），对于强迫症很难忍

3 移动端发布主题是右上角的小图标，我个人认为不是很明显，是否改为像电脑端那样的蓝底白字按钮会好一点？

4 页面的“夜间模式”要是能跟随系统就更好了

5 链接预览我这里显示不出来，一直在转圈圈。另外就算是可以显示出来我建议不要占据太大版面，毕竟只是辅助，不要掩盖主题内容

6 搜索功能不好用，比如我搜“bilibili”可以搜到内容，搜“bili”就搜不到，搜单个字，比如“是”也返回“空空如也”

7 建议增加主题的阅读次数计数

8 建议增加分享功能，比如将贴子分享到朋友圈或聊天群里

**Comment by SignorMercurio** [comment]
2 Wontfix
3 暂时 Wontfix
4 目前可以切换成“跟随系统”模式
5 无法显示问题已修复，空间占据问题见 #22 
6 见 #4 
7 Done

**Comment by jjaychen1e** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [屏幕宽度不足时显示错位问题 & 分享功能](https://trello.com/c/9Cur0ftK/12-%E5%B1%8F%E5%B9%95%E5%AE%BD%E5%BA%A6%E4%B8%8D%E8%B6%B3%E6%97%B6%E6%98%BE%E7%A4%BA%E9%94%99%E4%BD%8D%E9%97%AE%E9%A2%98-%E5%88%86%E4%BA%AB%E5%8A%9F%E8%83%BD)

**Comment by SignorMercurio** [comment]
1 已修复
2 补充：点击提示消息本身会进入帖子并跳转到对应位置，此时该提示消息会被标为已读
8 与 #34 合并
