### ISSUE TITLE
图床采用七牛云对象存储，需要已备案域名作为 CDN

### ISSUE THREAD

**Issue by SignorMercurio** [ECNU-Forum/ECNU-Forum#2]

**Comment by SignorMercurio** [comment]
https://jacobruan.com/flarum-uses-tencent-cloud-cos-storage/

**Comment by jjaychen1e** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [图床采用七牛云对象存储，需要已备案域名作为 CDN](https://trello.com/c/8PvmRosA/17-%E5%9B%BE%E5%BA%8A%E9%87%87%E7%94%A8%E4%B8%83%E7%89%9B%E4%BA%91%E5%AF%B9%E8%B1%A1%E5%AD%98%E5%82%A8%EF%BC%8C%E9%9C%80%E8%A6%81%E5%B7%B2%E5%A4%87%E6%A1%88%E5%9F%9F%E5%90%8D%E4%BD%9C%E4%B8%BA-cdn)
