### ISSUE TITLE
桌面模式下左侧导航栏的固定与单独滚动

### ISSUE THREAD

**Issue by jtchen2k** [ECNU-Forum/ECNU-Forum#21]

**Comment by jjaychen1e** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [桌面模式下左侧导航栏的固定与单独滚动](https://trello.com/c/jpEUTfp5/14-%E6%A1%8C%E9%9D%A2%E6%A8%A1%E5%BC%8F%E4%B8%8B%E5%B7%A6%E4%BE%A7%E5%AF%BC%E8%88%AA%E6%A0%8F%E7%9A%84%E5%9B%BA%E5%AE%9A%E4%B8%8E%E5%8D%95%E7%8B%AC%E6%BB%9A%E5%8A%A8)

**Comment by panini519** [comment]
近期主题数量增多，浏览版块后（大部分）需要重新滚动到初始位置，再选择分区。

**Comment by panini519** [comment]
参考：[Flarum 中文社区] 框架

**Comment by oceanlvr** [comment]
左侧 sticky 固定了

**Comment by SignorMercurio** [comment]
重新调整了下 css，目前鼠标移动到标签导航会出现滚动条了

**Comment by SignorMercurio** [comment]
功能已封装为 Flarum 插件：https://github.com/ECNU-Forum/sticky-sidenav
