### ISSUE TITLE
移动端 Link Preview 占用空间过大，应限制最长字数

### ISSUE THREAD

**Issue by jjaychen1e** [ECNU-Forum/ECNU-Forum#22]
![IMG_5854](https://user-images.githubusercontent.com/31304335/159047547-15d42bf8-ea70-45cb-b46a-97d702588ded.PNG)

**Comment by jjaychen1e** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [移动端 Link Preview 占用空间过大，应限制最长字数](https://trello.com/c/lIZ9F7Ug/15-%E7%A7%BB%E5%8A%A8%E7%AB%AF-link-preview-%E5%8D%A0%E7%94%A8%E7%A9%BA%E9%97%B4%E8%BF%87%E5%A4%A7%EF%BC%8C%E5%BA%94%E9%99%90%E5%88%B6%E6%9C%80%E9%95%BF%E5%AD%97%E6%95%B0)

**Comment by homanw104** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [需要用户举报、禁言机制](https://trello.com/c/YVu5o4LY/34-%E9%9C%80%E8%A6%81%E7%94%A8%E6%88%B7%E4%B8%BE%E6%8A%A5%E3%80%81%E7%A6%81%E8%A8%80%E6%9C%BA%E5%88%B6)

**Comment by SignorMercurio** [comment]
example: https://ecnu.im/d/130/62

**Comment by SignorMercurio** [comment]
fixed
