### ISSUE TITLE
常见问题解答里的错误

### ISSUE THREAD

**Issue by chguw** [ECNU-Forum/ECNU-Forum#25]
在“学校邮箱是什么？”章节，“忘记密码”这一段，“学生邮箱密码重新申请”应该是“学生邮箱密码重置申请”，是“重置”而非“重新”。

常见问题页面 https://ecnu.im/p/2-FAQ

**Comment by SignorMercurio** [comment]
企业微信里的原文是什么？想确认一下，我暂时好像访问不了。

**Comment by chguw** [comment]
原文见这里：

<a href="https://imgtu.com/i/qkzkhn"><img src="https://s1.ax1x.com/2022/03/19/qkzkhn.jpg" alt="qkzkhn.jpg" border="0" /></a>

**Comment by SignorMercurio** [comment]
已修改

**Comment by jjaychen1e** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [常见问题解答里的错误](https://trello.com/c/N7xSwYFS/25-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94%E9%87%8C%E7%9A%84%E9%94%99%E8%AF%AF)
