### ISSUE TITLE
电脑端页面显示 BUG

### ISSUE THREAD

**Issue by chguw** [ECNU-Forum/ECNU-Forum#26]
需要鼠标移动到贴子上面才能显示“赞”、“回复”和表情等，如果鼠标移走了就什么都看不到了，包括给贴子贴上去的表情

<a href="https://imgtu.com/i/qEPOG4"><img src="https://s1.ax1x.com/2022/03/19/qEPOG4.png" alt="qEPOG4.png" border="0" /></a>

**Comment by SignorMercurio** [comment]
是的，这是预期行为

**Comment by chguw** [comment]
移动端就都能看到

**Comment by SignorMercurio** [comment]
> 移动端就都能看到

是的，因为移动端没有鼠标，不能使用这种灵活的方式

**Comment by chguw** [comment]
但是给贴子贴上去的表情也就看不到了

**Comment by SignorMercurio** [comment]
> 但是给贴子贴上去的表情也就看不到了

确认一下，移动端看不到贴的表情吗？

**Comment by chguw** [comment]
移动端可以看到表情，所有的都能看到
电脑端都看不到，包括表情

**Comment by SignorMercurio** [comment]
> 移动端可以看到表情，所有的都能看到 电脑端都看不到，包括表情

我看了下，电脑端移动鼠标到对应帖子上可以看到表情呀

**Comment by chguw** [comment]
是的，只能移动鼠标上去看了。嗯，如果是有意的话，那就不是 BUG 了

**Comment by SignorMercurio** [comment]
是的，移动鼠标才能看到贴的表情、赞按钮和回复按钮是电脑端的预期行为

**Comment by jjaychen1e** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [手机端主题的阅读次数没有夜间模式适配](https://trello.com/c/hp8aS6DX/16-%E6%89%8B%E6%9C%BA%E7%AB%AF%E4%B8%BB%E9%A2%98%E7%9A%84%E9%98%85%E8%AF%BB%E6%AC%A1%E6%95%B0%E6%B2%A1%E6%9C%89%E5%A4%9C%E9%97%B4%E6%A8%A1%E5%BC%8F%E9%80%82%E9%85%8D)
