### ISSUE TITLE
只允许 ecnu.edu.cn 邮箱注册

### ISSUE THREAD

**Issue by SignorMercurio** [ECNU-Forum/ECNU-Forum#3]

**Comment by jjaychen1e** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [只允许 ecnu.edu.cn 邮箱注册](https://trello.com/c/JoWYsdwJ/18-%E5%8F%AA%E5%85%81%E8%AE%B8-ecnueducn-%E9%82%AE%E7%AE%B1%E6%B3%A8%E5%86%8C)
