### ISSUE TITLE
标签项浮窗化 & 置于顶栏

### ISSUE THREAD

**Issue by panini519** [ECNU-Forum/ECNU-Forum#37]
现状：查看特定帖子时，顶部无全局导航，不支持直接跳转至其他一级标签/二级标签。

改进：
标签移动至顶栏，点击出现浮窗。
<img width="547" alt="image" src="https://user-images.githubusercontent.com/101924843/159140851-ed5e956d-164e-4c17-962b-a2ea68540c3b.png">

**Comment by asa133** [comment]
不用全部平铺，用一个下拉的级联列表组件就可以了
选项就是 icon+标签文字
