### ISSUE TITLE
[BUG] 未登陆状态菜单栏切换主题按钮会有三个状态

### ISSUE THREAD

**Issue by jjaychen1e** [ECNU-Forum/ECNU-Forum#38]
### 当前行为

Light Mode -> Setting -> Dark Mode
但是 Setting 无效

https://user-images.githubusercontent.com/31304335/159145934-4d574c41-d50a-4c1b-8438-6ef1d72aeb43.mov

### 平台信息

PC

### 浏览器信息

Chrome

### 用户状态信息

未登录

**Comment by jjaychen1e** [comment]
<img width="230" alt="image" src="https://user-images.githubusercontent.com/31304335/159146154-00cd8fe4-82cf-443f-a189-364523fd0152.png">

登录状态这个的图标也不对，可以一起修复

**Comment by SignorMercurio** [comment]
这个图标只是看起来像齿轮的太阳图标。。？

**Comment by SignorMercurio** [comment]
另外当前行为是 Light -> Auto -> Dark，中间 Auto 不变是因为跟随了系统

**Comment by jjaychen1e** [comment]
> 这个图标只是看起来像齿轮的太阳图标。。？

有 道 理。那后面换个更明显的图标，再加个 alt 标签就可以了。

**Comment by SignorMercurio** [comment]
那先 close 了，问题不大

**Comment by jjaychen1e** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Light Mode icon 更换](https://trello.com/c/eLSoJCQZ/47-light-mode-icon-%E6%9B%B4%E6%8D%A2)
