### ISSUE TITLE
中文分词导致的搜索问题

### ISSUE THREAD

**Issue by SignorMercurio** [ECNU-Forum/ECNU-Forum#4]

**Comment by SignorMercurio** [comment]
https://extiverse.com/extension/blomstra/search 需要本地起 Elastic 服务

**Comment by SignorMercurio** [comment]
> https://extiverse.com/extension/blomstra/search

需要本地起 Elastic 服务

**Comment by SignorMercurio** [comment]
https://discuss.flarum.org.cn/d/1216 可能需要把数据库迁移至 mysql

**Comment by jjaychen1e** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [中文分词导致的搜索问题](https://trello.com/c/ctXaYOE6/8-%E4%B8%AD%E6%96%87%E5%88%86%E8%AF%8D%E5%AF%BC%E8%87%B4%E7%9A%84%E6%90%9C%E7%B4%A2%E9%97%AE%E9%A2%98)
