### ISSUE TITLE
楼主标识的显示问题及删除逻辑

### ISSUE THREAD

**Issue by panini519** [ECNU-Forum/ECNU-Forum#40]
### 当前行为

1）进入贴内一楼不显示楼主标识，重新刷新后才显示
2）一楼删帖后二楼用户自动成为楼主

### 预期行为

1）一楼始终显示楼主标识，无需刷新
2）修改删除逻辑：一楼楼主删帖后当前帖无楼主，即二楼不会自动成为新楼主。

### 复现步骤

显示问题目前无法复现

### 平台信息

PC

### 浏览器信息

Chrome, Safari

### 用户状态信息

版主

### 补充信息

<img width="374" alt="image" src="https://user-images.githubusercontent.com/101924843/159148274-89125b91-8a48-432a-a778-4c88cf951ddb.png">

**Comment by cubercsl** [comment]
直接访问页面和从列表点进页面时发起的请求有所不同~可能是这个原因造成的。

**Comment by cubercsl** [comment]
https://github.com/ECNU-Forum/topic-starter-label/commit/9c3e06f161c76d2d3c16f7df873ec12bac1b3339
