### ISSUE TITLE
[BUG] 投票编辑框未保存消失问题

### ISSUE THREAD

**Issue by WonderTool** [ECNU-Forum/ECNU-Forum#41]
### 当前行为

投票编辑框编辑到一半，鼠标移出框外时编辑框消失，且未保存。

### 预期行为

提交前不会消失，更酷的话自动保存

### 复现步骤

1. 发布主题，发起投票，输入内容
2. 鼠标编辑框外点击
3. 编辑框就消失了
4. 重新点开，曾输入的内容均无保存

### 平台信息

PC

### 浏览器信息

Chrome

### 用户状态信息

版主

**Comment by chguw** [comment]
同遇到，应该是只要没有“提交”投票，就不会保存，鼠标在编辑框外点击就取消了“发起投票”。另外“允许查看投票人”意义没有“匿名投票”清楚，是只有楼主可以查看还是所有人都可以查看，而且“允许”好像是在鼓励打开这个选项

**Comment by SignorMercurio** [comment]
在编辑框外点击后编辑框消失是预期行为，目的是为了更方便地关闭编辑弹窗。提交按钮的目的在于暂时保存已编辑的投票，暂时不会做自动保存的功能。
