### ISSUE TITLE
[BUG] Link Preview 有几率获取 GitHub 信息失败

### ISSUE THREAD

**Issue by jjaychen1e** [ECNU-Forum/ECNU-Forum#42]
### 当前行为

<img width="1534" alt="image" src="https://user-images.githubusercontent.com/31304335/159149677-4539c8e1-16cf-43c4-bcd6-5378dce31d74.png">

### 平台信息

PC, Android, iOS, 其他

### 浏览器信息

Chrome, Safari

### 用户状态信息

普通用户, 版主, 管理员

**Comment by SignorMercurio** [comment]
由于使用了新的 link preview 插件，问题已修复
