### ISSUE TITLE
配置化 | 特定版块支持匿名 & 全部主题页关闭特定版块信息流

### ISSUE THREAD

**Issue by panini519** [ECNU-Forum/ECNU-Forum#43]
### 场景描述

1. 当前平台用户处于半匿名状态，易识别出其他用户的真实身份，建议新增匿名功能。匿名功能维护难度大，平台存在被举报风险，建议匿名功能仅对特定版块开放
2. 针对特定版块，大量发帖的情况，不建议在全部主题中显示（目前没有过滤主题的功能）

### 预期解决方案

1. 建议匿名功能仅对特定版块开放（eg 表白墙）
2. 针对特定版块（eg 表白墙），相关帖不在全部主题中显示

**Comment by panini519** [comment]
版块新增「表白」相关的也可以提在这个issue里   @Guowei Chen

**Comment by panini519** [comment]
版块新增「表白」相关的也可以提在这个issue里 @chguw

**Comment by panini519** [comment]
pending，等新增了需要配置化的版块再打开该issue

**Comment by SignorMercurio** [comment]
最近研究了匿名功能，工作量太大了，应该 wontfix。
