### ISSUE TITLE
让回复帖紧跟在被回复帖下方

### ISSUE THREAD

**Issue by SignorMercurio** [ECNU-Forum/ECNU-Forum#5]

**Comment by jjaychen1e** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [让回复帖紧跟在被回复帖下方](https://trello.com/c/5SQmPAXU/10-%E8%AE%A9%E5%9B%9E%E5%A4%8D%E5%B8%96%E7%B4%A7%E8%B7%9F%E5%9C%A8%E8%A2%AB%E5%9B%9E%E5%A4%8D%E5%B8%96%E4%B8%8B%E6%96%B9)

**Comment by WonderTool** [comment]
<img width="731" alt="image" src="https://user-images.githubusercontent.com/66750093/159312874-9178a094-d238-4d6d-a9c1-99bcc0b96844.png">
+ 显示楼数，方便用户回复及查看

**Comment by SignorMercurio** [comment]
光标移动到 mention 部分可以查看回复 / 被回复，点击则可以跳转到回复 / 被回复的帖子；这一功能暂时不必要。
