### ISSUE TITLE
[BUG] 安卓端下滚重复出现置顶帖

### ISSUE THREAD

**Issue by tianyilt** [ECNU-Forum/ECNU-Forum#50]
### 当前行为

在android端下滚，发现置顶帖重复出现。
验证方式如图所示，我用手机端的自动滚屏截图，可以看到，这个置顶帖多次出现。说明每次滚屏刷新都会的导致置顶帖重复出现
![Uploading Screenshot_20220321_032357_com.android.chrome.jpg…]()

### 预期行为

不会重复出现内容，按照排序继续显示新的帖子

### 复现步骤

手机访问，然后向下滚

### 平台信息

Android

### 浏览器信息

Chrome

### 用户状态信息

版主

**Comment by cubercsl** [comment]
安卓 Chrome 没有复现

**Comment by tianyilt** [comment]
虽然不知道为什么，但是今天的修复了
