### ISSUE TITLE
[BUG] “活动信息”的某些贴子不出现在“全部主题”里

### ISSUE THREAD

**Issue by chguw** [ECNU-Forum/ECNU-Forum#51]
### 当前行为

“活动信息”里的贴子不出现在“全部主题”里

<a href="https://imgtu.com/i/quMntU"><img src="https://s1.ax1x.com/2022/03/21/quMntU.png" alt="quMntU.png" border="0"></a>
<br>
<a href="https://imgtu.com/i/quMmkT"><img src="https://s1.ax1x.com/2022/03/21/quMmkT.png" alt="quMmkT.png" border="0"></a>

### 预期行为

所有的贴子都应该出现在“全部信息”里

### 平台信息

PC

### 浏览器信息

Chrome

### 用户状态信息

版主

**Comment by SignorMercurio** [comment]
![image](https://user-images.githubusercontent.com/32540679/159260506-ca3b7692-763f-4b80-b538-a0e6b6dc515a.png)

会出现在全部主题，排序在更晚发布的主题后面是因为那个主题的最新回复时间更晚

**Comment by panini519** [comment]
全部主题默认按照「最新回复」排序。如果要看根据帖主发布时间排序的结果，需要通过「新鲜出炉」筛选。
很多楼主会去顶贴，刷新到最上方

**Comment by chguw** [comment]
是的，我一直是按照“最新回复”排序的，刚刚确实是没有，因为我上上下下找了很多页，奇怪的是现在有了，我也不清楚怎么回事

**Comment by chguw** [comment]
> 全部主题默认按照「最新回复」排序。如果要看根据帖主发布时间排序的结果，需要通过「新鲜出炉」筛选。 很多楼主会去顶贴，刷新到最上方

【一周 CP】的贴子发布之后就没有人回帖，所以发布时间其实就是最后回复时间，所以在“全部主题”页面，也应该出现在“回复于 1 小时前”和“回复于 3 小时前”之间

**Comment by chguw** [comment]
“本校金融考研资讯”之所以是“发布于 3 小时前”是因为它也是没有人回复，所以发布时间就是最后回复时间

**Comment by panini519** [comment]
看来是bug

**Comment by SignorMercurio** [comment]
> “本校金融考研资讯”之所以是“发布于 3 小时前”是因为它也是没有人回复，所以发布时间就是最后回复时间

我看截图里 “本校金融考研资讯” 有 1 条回复？这条回复可能并不是 3 小时前的？

**Comment by chguw** [comment]
> > “本校金融考研资讯”之所以是“发布于 3 小时前”是因为它也是没有人回复，所以发布时间就是最后回复时间
> 
> 我看截图里 “本校金融考研资讯” 有 1 条回复？这条回复可能并不是 3 小时前的？

那是因为我都没有查看过。对于没有查看或有新回复的贴子，上面的数字是未看回复数，不是全部回复数。预览不是也能看出来没有人回复嘛。原文这里 https://ecnu.im/d/379

**Comment by SignorMercurio** [comment]
了解了，问题需要复现下

**Comment by chguw** [comment]
再次发现。图 1 中 13 小时前回复的贴子不出现在图 2 里：

### **图 1：**
<a href="https://imgtu.com/i/qy679A"><img src="https://s1.ax1x.com/2022/03/29/qy679A.jpg" alt="qy679A.jpg" border="0" /></a>


### **图 2：**
<a href="https://imgtu.com/i/qy6ohd"><img src="https://s1.ax1x.com/2022/03/29/qy6ohd.jpg" alt="qy6ohd.jpg" border="0" /></a>

**Comment by SignorMercurio** [comment]
了解了，不过不清楚什么情况下会复现？暂时没想到引起这种情况的原因

**Comment by SignorMercurio** [comment]
应该修复了。
