### ISSUE TITLE
[BUG] 标签栏宽度不足

### ISSUE THREAD

**Issue by chguw** [ECNU-Forum/ECNU-Forum#55]
### 当前行为

当展开二级标签的时候标签栏的宽度就变得不足，会出现看不见的横向滚动条，在触摸设备上可以滑到如图所示的状态：
<br>
<a href="https://imgtu.com/i/qKlXqA"><img src="https://s1.ax1x.com/2022/03/22/qKlXqA.jpg" alt="qKlXqA.jpg" border="0" /></a>

### 预期行为

始终有足够的宽度，不允许横向滑动

### 平台信息

iOS

### 浏览器信息

Safari

### 用户状态信息

版主

### 补充信息

iPad

**Comment by SignorMercurio** [comment]
已修复
