### ISSUE TITLE
[BUG] 标签栏的跳动

### ISSUE THREAD

**Issue by chguw** [ECNU-Forum/ECNU-Forum#56]
### 当前行为

到达页面底部下拉加载更多主题时标签栏会出现跳动的情况。

例如在这个例子中，当前标签栏底部是“灌水闲聊”，到达了页面底部下拉加载之后，跳出了“实验问卷”，等页面加载完成，“实验问卷”又跳回去了。

例子见 https://youtu.be/1J8FYsIWXj4

### 预期行为

没有跳动

### 平台信息

PC

### 浏览器信息

Chrome

### 用户状态信息

版主

**Comment by SignorMercurio** [comment]
~~我好像不知道这个怎么修~~

**Comment by oceanlvr** [comment]
导致这个的原因是sticky相对的视口元素应该是左侧 sidebar 的 nearest scrolling ancestor 元素计算。在这个例子中是 window 视口。

当滑动右边的帖子到底，但是左侧高度不够的时候，左侧现在因为加了 scroll 所以呈现出的是滚动到底部，当右侧帖子加载完毕，帖子撑开了整个 window 此时计算 nearest scrolling ancestor 时发现此时没有到达底部，所以 sidebar 再次回到了上面的帖子（不表现为滚动到底部）。

感觉没有太大修复的必要QAQ，应该不太影响用户体验。

**Comment by oceanlvr** [comment]
要修复可能要解决让滑动到底的时候不影响左侧元素的滑动。（不让左侧滑动 除非它 hover 到 sidebar 上滑动）

**Comment by SignorMercurio** [comment]
> 导致这个的原因是sticky相对的视口元素应该是左侧 sidebar 的 nearest scrolling ancestor 元素计算。在这个例子中是 window 视口。
> 
> 当滑动右边的帖子到底，但是左侧高度不够的时候，左侧现在因为加了 scroll 所以呈现出的是滚动到底部，当右侧帖子加载完毕，帖子撑开了整个 window 此时计算 nearest scrolling ancestor 时发现此时没有到达底部，所以 sidebar 再次回到了上面的帖子（不表现为滚动到底部）。
> 
> 感觉没有太大修复的必要QAQ，应该不太影响用户体验。

了解了，感谢
