### ISSUE TITLE
[BUG] 个人页面标签跳动

### ISSUE THREAD

**Issue by chguw** [ECNU-Forum/ECNU-Forum#57]
### 当前行为

在个人页面下拉加载时左侧标签会出现先下移再跳回的奇怪行为（对不起管理员，以你为例子）

视频见 https://youtu.be/pjudFzXcLiQ

### 预期行为

随页面滚动消失或固定在页面上不移动不跳动

### 平台信息

PC

### 浏览器信息

Chrome

### 用户状态信息

版主

**Comment by chguw** [comment]
我知道为什么 Win10 有这么多 BUG 了，它可能采用了相似的开发流程——来自疫情文学 ;)

**Comment by oceanlvr** [comment]
@chguw  修了下样式，应该fix这个问题了
