### ISSUE TITLE
可以增加一个回到顶部的按钮

### ISSUE THREAD

**Issue by jtchen2k** [ECNU-Forum/ECNU-Forum#6]

**Comment by SignorMercurio** [comment]
现在应该有了

**Comment by SignorMercurio** [comment]
调整了下，移动端也能看到了

**Comment by SignorMercurio** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [可以增加一个回到顶部的按钮](https://trello.com/c/9RwzpJAx/19-%E5%8F%AF%E4%BB%A5%E5%A2%9E%E5%8A%A0%E4%B8%80%E4%B8%AA%E5%9B%9E%E5%88%B0%E9%A1%B6%E9%83%A8%E7%9A%84%E6%8C%89%E9%92%AE)
