### ISSUE TITLE
[FEAT] 让页面左侧标签栏随页面滚动，不要固定在页面上

### ISSUE THREAD

**Issue by chguw** [ECNU-Forum/ECNU-Forum#64]
### 场景描述

目前页面左侧的标签栏是固定在页面上的，就是无论页面下翻多少页，标签栏始终可见。这样的设置是方便了一点标签之间的转跳，但还存在如下问题：

1. 交互逻辑混乱。由于标签栏不随整体页面滚动，而贴子可以随页面滚动，所以标签栏与贴子部分的逻辑是不同的，标签栏的滚动应该不依赖于贴子部分。但是目前的情况是，一方面如果贴子部分的高度不够，标签栏无法滚动出全部标签。只有贴子部分加载了更多了之后，页面高度足够了，标签栏才可以顺利滚动到底部。另一方面在标签栏上滚动鼠标滚轮，如果到达了标签顶部或底部，页面就会跟随滚动。这样分不清到底是在滚动标签栏还是在滚动页面；
2. 如果标签过多实际上比之不固定更为不便。因为滚动逻辑比较混乱，不滚动可能还好，但是如果需要滚动，比如标签很多的情况，由于有点难以捉摸行为后果，实际上固定在页面上并不比行为可预测的随页面滚动更好用；
3. “发布主题”按钮随页面滚动，心理上它应该一直与标签栏的这些标签在一起，这会造成在翻了很多贴子之后找“发布主题”按钮时一直在滚动却始终看不到的情况；
4. 引入潜在 BUG。目前对于标签栏固定的实现还不完善，我已经反馈了一些 BUG，今天又发现两个 BUG（见附图）；
5. 影响页面加载速度。这是我的猜测，固定标签栏需要页面进行额外的计算，增加加载负担，降低加载速度。

关于固定标签栏是否有必要：

我的看法是没有必要。“全部主题”是全部信息的汇聚地，在这里浏览翻页（就是不停地“加载更多”主题）可以看到全部标签的信息（前提是没有标签的信息被隐藏），不需要转跳到其他标签。而在其他标签里浏览的时候，如果需要转跳，更多时候是转跳到“全部主题”。只有快速翻看各个标签的贴子时才会在标签之间频繁跳动。标签的固定很大一部分原因是为了方便在浏览贴子时跳到其他标签，但是这种需求可能没有想像中那么多吧。

当然说到底，以上可以总结为“偏见”，都固定了这么久，我始终不适应。

附图，图一是“全部主题”标签显示不全，图二是标签栏不显示。这不是大问题，刷新一下就没有了。

**图一：**
<a href="https://imgtu.com/i/qsjUbD"><img src="https://s1.ax1x.com/2022/03/29/qsjUbD.png" alt="qsjUbD.png" border="0" /></a>

**图二：**
<a href="https://imgtu.com/i/qsjNDO"><img src="https://s1.ax1x.com/2022/03/29/qsjNDO.png" alt="qsjNDO.png" border="0" /></a>

### 预期解决方案

让页面左侧标签栏随页面滚动，不要固定在页面上

**Comment by asa133** [comment]
固定更好，通常做法是鼠标悬停至左边栏、右边栏有额外滚动条，跟随滚动如果要找标签岂不是要一直上滑，无法继续看主题，不符合交互规范。

![mockupmirror](https://user-images.githubusercontent.com/85801933/160599698-880e8203-5ff6-4a7e-a670-c773bf85f650.png)

基本上可以参考各类知识库产品的目录边栏，三栏式分布和微博、twitter等大产品web也是一样的

**Comment by SignorMercurio** [comment]
看来关于这个问题还需要一些讨论？

**Comment by WonderTool** [comment]
总体同意 Chelsea 的建议，目前左侧标签固定我个人很适应。我会快速跳转不同标签来查看分区中新增/活跃的帖子，相信固定更符合交互规范。另，发布贴文的标签只要在方便点选的位置，固定在屏幕上即可。左/右上/下角、固定在菜单栏、乃至移动端的右下角（像 twitter 那样）都可。🤔

**Comment by panini519** [comment]
这个左侧固定的需求当时是我提出的，我解释下为什么一定要做：
1、用户滑动在任意帖的时候，可以随时切换标签。如果未固定，需要点击右下角回到顶部，再进行选择，流程复杂。
2、与大部分用户的使用习惯一致，具有较多标签的网站也是左侧固定的。
目前上线后出现了几个BUG：如滑动之后，发布按钮被隐藏，交互逻辑问题。对此，我建议有bug修bug，大家努力想办法修。eg 发布的位置可以参考@Chelsea的调整。不建议因为bug就削掉这个功能，更新上线后又下线对用户来说也不太友好。

另，以上仅供参考，谢谢Guowei报的问题！

**Comment by chguw** [comment]
谢谢帕尼尼的回复。是的，这个功能需求与你提的是相反的，我也赞同如果大家都适应了就不要“下线”这个功能，但是从另外一个角度看，这也是在对论坛做优化。我是希望保留这么一个有待商榷的空间，自然目前也没有迫切的需求和必要，但是如果有一天需要做出改变，我希望这个贴子能提醒开发者修改的本意与理由。

**Comment by SignorMercurio** [comment]
为了解决问题 1 和问题 2，当前版本中当用户鼠标移动到标签导航部分时会出现滚动条，可以清晰地看到标签导航部分是否已经滚动到底，从而方便区分标签滚动和页面滚动。

问题 3 是有意为之，从而留出更多空间给更常用的标签导航。同时，页面右下角有“回到顶部“按钮。

问题 4 涉及的 bug 已修复。

问题 5 中额外的样式带来的性能开销极小，可以忽略不计。
