### ISSUE TITLE
[FEAT] 手机端缺少“忽视”主题功能

### ISSUE THREAD

**Issue by chguw** [ECNU-Forum/ECNU-Forum#65]
### 场景描述

手机端缺少“忽视”主题功能，目前该功能只有电脑端有，功能名为“忽视中”

### 预期解决方案

建议手机端增加此功能

**Comment by SignorMercurio** [comment]
![1201648624957_ pic](https://user-images.githubusercontent.com/32540679/160774822-373ebec1-44bf-421b-9674-02b8d51b237b.jpg)

这个问题怎么复现，我这里似乎能看到

**Comment by chguw** [comment]
哦，我知道了，管理员是进入贴子之后点标题栏下面的下拉菜单，我是直接在“全部主题”页面右滑相应主题，底部弹出的菜单里寻找。见图（只有“关注”，如果关注了就会变成“取消关注”）：

<a href="https://imgtu.com/i/q2lFKA"><img src="https://s1.ax1x.com/2022/03/30/q2lFKA.jpg" alt="q2lFKA.jpg" border="0" /></a>

**Comment by SignorMercurio** [comment]
是的，在电脑端的话在帖子外面也只有关注，进入帖子后才会有更多别的选项。
