### ISSUE TITLE
[FEAT] 增加关注标签功能

### ISSUE THREAD

**Issue by chguw** [ECNU-Forum/ECNU-Forum#68]
### 场景描述

目前只能关注主题，不能定向接收感兴趣标签新帖的提醒，如果有关注标签的功能，提供标签内新帖提醒，个人认为将会非常有用

### 预期解决方案

同上

**Comment by SignorMercurio** [comment]
现在可以关注标签了：

![image](https://user-images.githubusercontent.com/32540679/161420662-2d39709e-cdd8-4d5f-8add-289dc00835c6.png)
