### ISSUE TITLE
[FEAT] 在贴子内容页面增加固定的标签栏

### ISSUE THREAD

**Issue by chguw** [ECNU-Forum/ECNU-Forum#69]
### 场景描述

我猜测，在浏览贴子标题时有（甚至在翻了很多页之后——因为如果不翻页的话就体现不出固定标签的必要——仍然有很强的）直接转跳到其他标签（板块）的需求并且符合“交互规范”（见 https://github.com/ECNU-Forum/ECNU-Forum/issues/64 ），那么在浏览贴子内容时更是如此，例如回到这个贴子所在的标签（板块），或是直接跳到其他标签（板块）。目前论坛提供的功能是，在电脑端当鼠标滑到页面左侧展开“全部主题”列表，但是这只是“全部主题”，体验甚至不如点击页面顶部的 logo，无法提供符合“交互规范”的功能。

附言，有个类似的功能需求，不过不一样 https://github.com/ECNU-Forum/ECNU-Forum/issues/37

### 预期解决方案

在贴子内容页面（例如 https://ecnu.im/d/429 ）增加固定的标签栏，就像在“全部主题”页面（ https://ecnu.im/ ）一样

**Comment by SignorMercurio** [comment]
See #37
