### ISSUE TITLE
在服务器上起一个 flarum 的 docker，用于测试

### ISSUE THREAD

**Issue by SignorMercurio** [ECNU-Forum/ECNU-Forum#7]
参考：https://github.com/mondediefr/docker-flarum

**Comment by SignorMercurio** [comment]
考虑到旧站还能利用，优先级不太高

**Comment by jjaychen1e** [comment]
我本地在用这个 repo 的 docker 做插件测试，如果站点分出一个测试环境用于测试是挺方便的。不过Docker 内存占用太大，跑在服务器上可能有些压力？

**Comment by SignorMercurio** [comment]
> 我本地在用这个 repo 的 docker 做插件测试，如果站点分出一个测试环境用于测试是挺方便的。不过Docker 内存占用太大，跑在服务器上可能有些压力？

嗯，所以打算先用旧站测试

**Comment by oceanlvr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CICD / docker 化测试环境](https://trello.com/c/W6ivIfpz/9-cicd-docker-%E5%8C%96%E6%B5%8B%E8%AF%95%E7%8E%AF%E5%A2%83)
