### ISSUE TITLE
[FEAT] 回复贴子与关注贴子解绑

### ISSUE THREAD

**Issue by chguw** [ECNU-Forum/ECNU-Forum#70]
### 场景描述

目前论坛的行为是，回复了贴子则自动关注该贴子，这个行为与回复而不关注相比具有一些不合理的地方：
1. 如果不想关注贴子则每次回复之后都要去取关贴子，这比当想关注再去关注只需点一次成本高很多；
2. 回复与关注是两个行为，两者是分离的（至于为何会出现回复贴子而不想关注的情况，我举个例子，就像每次我路过这个贴子，我随便看一眼，有什么想说的就回复一下，但是至于以后谁还来回复了，回复了什么，我不想每个都接到通知，不遗漏任何信息的通知是一种更深入的参与，我参与这个贴子纯粹只是一时的机缘与兴趣）；
3. 关注和回复合二为一带来的是深度卷入，不想深度卷入就会被排除在参与讨论之外（为什么这么说呢，就像三块钱的早餐，我把定价抬到了六块钱，那么就会限制一大批不想吃六块钱早餐的人），不利于自由表达；
4. 我认为论坛应努力降低沟通交流的成本，包括发贴的成本（可以很轻松自在地发贴，不要去翻陈年旧贴，不要努力思考用哪个标签好，不要考虑这个是考研信息好像论坛不让发，这个是招聘信息好像会引起某些人的焦虑；可以想参与就参与，想退出就退出，不要像一些商家一样，一旦注册了就天天发垃圾短信，还要主动去退订），包括看贴的成本（去掉影响速度的不一定每个人都需要的功能，提高每个人都能感受到的加载速度；去掉华而不实的费神费眼的低对比度配色，自然明确的配色才是应该追求的东西），包括参与的成本（有个清晰明确的守则，对自己的行为有预期，不会被莫名其妙地加要求，不会被莫名其妙地合并、移动、改标题，对于不合理的守则可以提出修改要求）。

第四点只是个人看法和建议，供你们参考。另外附上一个相关但看似相反的功能需求 https://github.com/ECNU-Forum/ECNU-Forum/issues/33

### 预期解决方案

解绑回复与关注

**Comment by SignorMercurio** [comment]
![image](https://user-images.githubusercontent.com/32540679/161742722-13359533-84dd-49e7-a9c7-f26c8c525790.png)

**Comment by SignorMercurio** [comment]
功能已存在。
