### ISSUE TITLE
[BUG] 无法预览的网址也不能打开

### ISSUE THREAD

**Issue by chguw** [ECNU-Forum/ECNU-Forum#72]
### 当前行为

【问题描述】见此贴 https://ecnu.im/d/572 ，贴内包含一个网址，无法预览，也无法打开

### 预期行为

【改进建议】希望对于无法预览的网址不要屏蔽链接

### 平台信息

iOS

### 浏览器信息

Safari

### 用户状态信息

普通用户

**Comment by jjaychen1e** [comment]
fixed: https://github.com/ECNU-Forum/flarum-link-preview/commit/ac591a47ad620a2b2f20530749e665e59d5d2d95
