### ISSUE TITLE
[FEAT] 支持表格语法

### ISSUE THREAD

**Issue by TrainFun** [ECNU-Forum/ECNU-Forum#75]
### 场景描述

尽管有序列表和无序列表已经满足大部分情况的使用, 在某些情况下, 使用表格会让内容更有条理. 

### 预期解决方案

类似Github风格的表格.

```markdown
| Header1 | Header2 | Header3 |
| :---    |  :---:  |    ---: |
| text1   |  text2  |   text3 |
```
| Header1 | Header2 | Header3 |
| :---    |  :---:  |    ---: |
| text1   |  text2  |   text3 |

**Comment by SignorMercurio** [comment]
已添加支持
