### ISSUE TITLE
[FEAT] 在中文和半角字符之间自动添加空格

### ISSUE THREAD

**Issue by CCXXXI** [ECNU-Forum/ECNU-Forum#77]
### 场景描述

浏览时发现部分帖子手动添加了空格，部分没有，有点不美观。
![image](https://user-images.githubusercontent.com/25550534/173839390-fc2c4e62-f219-4984-9482-609edb67df5a.png)

#### 方案一

- 编辑时自动添加空格
- （可选）此功能实装后，批量调整旧帖子的格式
- （可选）可以手动开关此功能

#### 方案二

- 渲染时自动添加空格
- （可选）可以手动开关此功能

### 补充信息

可以使用 [vinta/pangu.js](https://github.com/vinta/pangu.js)

**Comment by jtchen2k** [comment]
支持，理论上借助 [pangu.js](https://github.com/vinta/pangu.js) 可以纯在前端实现
