### ISSUE TITLE
iOS/Android 主屏幕图标

### ISSUE THREAD

**Issue by jjaychen1e** [ECNU-Forum/ECNU-Forum#8]
![](https://media.discordapp.net/attachments/953203247114489899/953862448664956958/IMG_5799.png)

解决方案: `<link rel="apple-touch-icon" href="/custom_icon.png">` （iOS 和 Android 都支持）

参考: [ConfiguringWebApplications](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html)

**Comment by SignorMercurio** [comment]
Thanks @JJAYCHEN1e

**Comment by jjaychen1e** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [iOS/Android 主屏幕图标](https://trello.com/c/YJiomeY6/20-ios-android-%E4%B8%BB%E5%B1%8F%E5%B9%95%E5%9B%BE%E6%A0%87)
