### ISSUE TITLE
iOS 微信内浏览器底部 Safe Area 不正常

### ISSUE THREAD

**Issue by jjaychen1e** [ECNU-Forum/ECNU-Forum#9]
![20220317195207](https://user-images.githubusercontent.com/31304335/158803990-e7c3b0e0-49f2-448d-9a1e-958f9ced3cf7.jpg)

cc: https://discord.com/channels/953203245940101170/953203247114489899/953984312540282890

**Comment by chguw** [comment]
这个很要紧，我觉得，因为使用微信打开的时候很多

**Comment by jjaychen1e** [comment]
fixed:

```html
<script>
  function isWeiXin() {
    var ua = window.navigator.userAgent.toLowerCase();
    return ua.match(/micromessenger/i) == 'micromessenger';
  }

  function setBottomPadding(element) {
    if (element) {
      element.style.setProperty('padding-bottom', '34px', 'important');
      return true;
    }
    return false;
  }

  if (isWeiXin()) {
    setTimeout(() => {
      if (!setBottomPadding(document.querySelector('.MobileTab-items'))) {
        setTimeout(() => {
          setBottomPadding(document.querySelector('.MobileTab-items'));
        }, 300);
      }
    }, 250);
  }
</script>
```

**Comment by jjaychen1e** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [iOS 微信内浏览器底部 Safe Area 不正常](https://trello.com/c/09ueVGSf/21-ios-%E5%BE%AE%E4%BF%A1%E5%86%85%E6%B5%8F%E8%A7%88%E5%99%A8%E5%BA%95%E9%83%A8-safe-area-%E4%B8%8D%E6%AD%A3%E5%B8%B8)
